//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace NijnCoach.Database
{
    #region Contexts
<<<<<<< HEAD

=======
    
>>>>>>> origin/DBconnect
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class NijnCoachEntities2 : ObjectContext
    {
        #region Constructors
<<<<<<< HEAD

        /// <summary>
        /// Initializes a new NijnCoachEntities2 object using the connection string found in the 'NijnCoachEntities2' section of the application configuration file.
        /// </summary>
        public NijnCoachEntities2()
            : base("name=NijnCoachEntities2", "NijnCoachEntities2")
=======
    
        /// <summary>
        /// Initializes a new NijnCoachEntities2 object using the connection string found in the 'NijnCoachEntities2' section of the application configuration file.
        /// </summary>
        public NijnCoachEntities2() : base("name=NijnCoachEntities2", "NijnCoachEntities2")
>>>>>>> origin/DBconnect
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
<<<<<<< HEAD

        /// <summary>
        /// Initialize a new NijnCoachEntities2 object.
        /// </summary>
        public NijnCoachEntities2(string connectionString)
            : base(connectionString, "NijnCoachEntities2")
=======
    
        /// <summary>
        /// Initialize a new NijnCoachEntities2 object.
        /// </summary>
        public NijnCoachEntities2(string connectionString) : base(connectionString, "NijnCoachEntities2")
>>>>>>> origin/DBconnect
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
<<<<<<< HEAD

        /// <summary>
        /// Initialize a new NijnCoachEntities2 object.
        /// </summary>
        public NijnCoachEntities2(EntityConnection connection)
            : base(connection, "NijnCoachEntities2")
=======
    
        /// <summary>
        /// Initialize a new NijnCoachEntities2 object.
        /// </summary>
        public NijnCoachEntities2(EntityConnection connection) : base(connection, "NijnCoachEntities2")
>>>>>>> origin/DBconnect
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
<<<<<<< HEAD

        #endregion

        #region Partial Methods

        partial void OnContextCreated();

        #endregion

        #region ObjectSet Properties

=======
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
>>>>>>> origin/DBconnect
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Address> Addresses
        {
            get
            {
                if ((_Addresses == null))
                {
                    _Addresses = base.CreateObjectSet<Address>("Addresses");
                }
                return _Addresses;
            }
        }
        private ObjectSet<Address> _Addresses;
<<<<<<< HEAD

=======
    
>>>>>>> origin/DBconnect
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Patient> Patients
        {
            get
            {
                if ((_Patients == null))
                {
                    _Patients = base.CreateObjectSet<Patient>("Patients");
                }
                return _Patients;
            }
        }
        private ObjectSet<Patient> _Patients;
<<<<<<< HEAD

=======
    
>>>>>>> origin/DBconnect
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PatientToAddress> PatientToAddresses
        {
            get
            {
                if ((_PatientToAddresses == null))
                {
                    _PatientToAddresses = base.CreateObjectSet<PatientToAddress>("PatientToAddresses");
                }
                return _PatientToAddresses;
            }
        }
        private ObjectSet<PatientToAddress> _PatientToAddresses;
<<<<<<< HEAD

=======
    
>>>>>>> origin/DBconnect
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Questionnairre> Questionnairres
        {
            get
            {
                if ((_Questionnairres == null))
                {
                    _Questionnairres = base.CreateObjectSet<Questionnairre>("Questionnairres");
                }
                return _Questionnairres;
            }
        }
        private ObjectSet<Questionnairre> _Questionnairres;
<<<<<<< HEAD

=======
    
>>>>>>> origin/DBconnect
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SpeechFile> SpeechFiles
        {
            get
            {
                if ((_SpeechFiles == null))
                {
                    _SpeechFiles = base.CreateObjectSet<SpeechFile>("SpeechFiles");
                }
                return _SpeechFiles;
            }
        }
        private ObjectSet<SpeechFile> _SpeechFiles;

        #endregion

        #region AddTo Methods
<<<<<<< HEAD

=======
    
>>>>>>> origin/DBconnect
        /// <summary>
        /// Deprecated Method for adding a new object to the Addresses EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAddresses(Address address)
        {
            base.AddObject("Addresses", address);
        }
<<<<<<< HEAD

=======
    
>>>>>>> origin/DBconnect
        /// <summary>
        /// Deprecated Method for adding a new object to the Patients EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPatients(Patient patient)
        {
            base.AddObject("Patients", patient);
        }
<<<<<<< HEAD

=======
    
>>>>>>> origin/DBconnect
        /// <summary>
        /// Deprecated Method for adding a new object to the PatientToAddresses EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPatientToAddresses(PatientToAddress patientToAddress)
        {
            base.AddObject("PatientToAddresses", patientToAddress);
        }
<<<<<<< HEAD

=======
    
>>>>>>> origin/DBconnect
        /// <summary>
        /// Deprecated Method for adding a new object to the Questionnairres EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToQuestionnairres(Questionnairre questionnairre)
        {
            base.AddObject("Questionnairres", questionnairre);
        }
<<<<<<< HEAD

=======
    
>>>>>>> origin/DBconnect
        /// <summary>
        /// Deprecated Method for adding a new object to the SpeechFiles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSpeechFiles(SpeechFile speechFile)
        {
            base.AddObject("SpeechFiles", speechFile);
        }

        #endregion

    }

    #endregion

    #region Entities
<<<<<<< HEAD

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName = "NijnCoachModel", Name = "Address")]
    [Serializable()]
    [DataContractAttribute(IsReference = true)]
    public partial class Address : EntityObject
    {
        #region Factory Method

=======
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NijnCoachModel", Name="Address")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Address : EntityObject
    {
        #region Factory Method
    
>>>>>>> origin/DBconnect
        /// <summary>
        /// Create a new Address object.
        /// </summary>
        /// <param name="street">Initial value of the Street property.</param>
        /// <param name="houseNo">Initial value of the HouseNo property.</param>
        /// <param name="postal">Initial value of the Postal property.</param>
        /// <param name="city">Initial value of the City property.</param>
        /// <param name="addressID">Initial value of the AddressID property.</param>
        public static Address CreateAddress(global::System.String street, global::System.SByte houseNo, global::System.String postal, global::System.String city, global::System.SByte addressID)
        {
            Address address = new Address();
            address.Street = street;
            address.HouseNo = houseNo;
            address.Postal = postal;
            address.City = city;
            address.AddressID = addressID;
            return address;
        }

        #endregion

        #region Primitive Properties
<<<<<<< HEAD

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
=======
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
>>>>>>> origin/DBconnect
        [DataMemberAttribute()]
        public global::System.String Street
        {
            get
            {
                return _Street;
            }
            set
            {
                OnStreetChanging(value);
                ReportPropertyChanging("Street");
                _Street = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Street");
                OnStreetChanged();
            }
        }
        private global::System.String _Street;
        partial void OnStreetChanging(global::System.String value);
        partial void OnStreetChanged();
<<<<<<< HEAD

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
=======
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
>>>>>>> origin/DBconnect
        [DataMemberAttribute()]
        public global::System.SByte HouseNo
        {
            get
            {
                return _HouseNo;
            }
            set
            {
                OnHouseNoChanging(value);
                ReportPropertyChanging("HouseNo");
                _HouseNo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HouseNo");
                OnHouseNoChanged();
            }
        }
        private global::System.SByte _HouseNo;
        partial void OnHouseNoChanging(global::System.SByte value);
        partial void OnHouseNoChanged();
<<<<<<< HEAD

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
=======
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
>>>>>>> origin/DBconnect
        [DataMemberAttribute()]
        public global::System.String Postal
        {
            get
            {
                return _Postal;
            }
            set
            {
                OnPostalChanging(value);
                ReportPropertyChanging("Postal");
                _Postal = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Postal");
                OnPostalChanged();
            }
        }
        private global::System.String _Postal;
        partial void OnPostalChanging(global::System.String value);
        partial void OnPostalChanged();
<<<<<<< HEAD

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
=======
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
>>>>>>> origin/DBconnect
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
<<<<<<< HEAD

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = true, IsNullable = false)]
=======
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
>>>>>>> origin/DBconnect
        [DataMemberAttribute()]
        public global::System.SByte AddressID
        {
            get
            {
                return _AddressID;
            }
            set
            {
                if (_AddressID != value)
                {
                    OnAddressIDChanging(value);
                    ReportPropertyChanging("AddressID");
                    _AddressID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AddressID");
                    OnAddressIDChanged();
                }
            }
        }
        private global::System.SByte _AddressID;
        partial void OnAddressIDChanging(global::System.SByte value);
        partial void OnAddressIDChanged();

        #endregion

<<<<<<< HEAD

    }

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName = "NijnCoachModel", Name = "Patient")]
    [Serializable()]
    [DataContractAttribute(IsReference = true)]
    public partial class Patient : EntityObject
    {
        #region Factory Method

=======
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NijnCoachModel", Name="Patient")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Patient : EntityObject
    {
        #region Factory Method
    
>>>>>>> origin/DBconnect
        /// <summary>
        /// Create a new Patient object.
        /// </summary>
        /// <param name="fname">Initial value of the Fname property.</param>
        /// <param name="lname">Initial value of the Lname property.</param>
        /// <param name="patientNo">Initial value of the PatientNo property.</param>
        /// <param name="age">Initial value of the Age property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        /// <param name="phoneNo">Initial value of the PhoneNo property.</param>
        public static Patient CreatePatient(global::System.String fname, global::System.String lname, global::System.SByte patientNo, global::System.SByte age, global::System.String email, global::System.Int64 phoneNo)
        {
            Patient patient = new Patient();
            patient.Fname = fname;
            patient.Lname = lname;
            patient.PatientNo = patientNo;
            patient.Age = age;
            patient.Email = email;
            patient.PhoneNo = phoneNo;
            return patient;
        }

        #endregion

        #region Primitive Properties
<<<<<<< HEAD

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
=======
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
>>>>>>> origin/DBconnect
        [DataMemberAttribute()]
        public global::System.String Fname
        {
            get
            {
                return _Fname;
            }
            set
            {
                OnFnameChanging(value);
                ReportPropertyChanging("Fname");
                _Fname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Fname");
                OnFnameChanged();
            }
        }
        private global::System.String _Fname;
        partial void OnFnameChanging(global::System.String value);
        partial void OnFnameChanged();
<<<<<<< HEAD

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
=======
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
>>>>>>> origin/DBconnect
        [DataMemberAttribute()]
        public global::System.String Lname
        {
            get
            {
                return _Lname;
            }
            set
            {
                OnLnameChanging(value);
                ReportPropertyChanging("Lname");
                _Lname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Lname");
                OnLnameChanged();
            }
        }
        private global::System.String _Lname;
        partial void OnLnameChanging(global::System.String value);
        partial void OnLnameChanged();
<<<<<<< HEAD

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = true, IsNullable = false)]
=======
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
>>>>>>> origin/DBconnect
        [DataMemberAttribute()]
        public global::System.SByte PatientNo
        {
            get
            {
                return _PatientNo;
            }
            set
            {
                if (_PatientNo != value)
                {
                    OnPatientNoChanging(value);
                    ReportPropertyChanging("PatientNo");
                    _PatientNo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PatientNo");
                    OnPatientNoChanged();
                }
            }
        }
        private global::System.SByte _PatientNo;
        partial void OnPatientNoChanging(global::System.SByte value);
        partial void OnPatientNoChanged();
<<<<<<< HEAD

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
=======
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
>>>>>>> origin/DBconnect
        [DataMemberAttribute()]
        public global::System.SByte Age
        {
            get
            {
                return _Age;
            }
            set
            {
                OnAgeChanging(value);
                ReportPropertyChanging("Age");
                _Age = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Age");
                OnAgeChanged();
            }
        }
        private global::System.SByte _Age;
        partial void OnAgeChanging(global::System.SByte value);
        partial void OnAgeChanged();
<<<<<<< HEAD

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
=======
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
>>>>>>> origin/DBconnect
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
<<<<<<< HEAD

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
=======
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
>>>>>>> origin/DBconnect
        [DataMemberAttribute()]
        public global::System.Int64 PhoneNo
        {
            get
            {
                return _PhoneNo;
            }
            set
            {
                OnPhoneNoChanging(value);
                ReportPropertyChanging("PhoneNo");
                _PhoneNo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PhoneNo");
                OnPhoneNoChanged();
            }
        }
        private global::System.Int64 _PhoneNo;
        partial void OnPhoneNoChanging(global::System.Int64 value);
        partial void OnPhoneNoChanged();

        #endregion

<<<<<<< HEAD

    }

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName = "NijnCoachModel", Name = "PatientToAddress")]
    [Serializable()]
    [DataContractAttribute(IsReference = true)]
    public partial class PatientToAddress : EntityObject
    {
        #region Factory Method

=======
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NijnCoachModel", Name="PatientToAddress")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PatientToAddress : EntityObject
    {
        #region Factory Method
    
>>>>>>> origin/DBconnect
        /// <summary>
        /// Create a new PatientToAddress object.
        /// </summary>
        /// <param name="patientID">Initial value of the PatientID property.</param>
        /// <param name="addressID">Initial value of the AddressID property.</param>
        public static PatientToAddress CreatePatientToAddress(global::System.String patientID, global::System.String addressID)
        {
            PatientToAddress patientToAddress = new PatientToAddress();
            patientToAddress.PatientID = patientID;
            patientToAddress.AddressID = addressID;
            return patientToAddress;
        }

        #endregion

        #region Primitive Properties
<<<<<<< HEAD

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = true, IsNullable = false)]
=======
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
>>>>>>> origin/DBconnect
        [DataMemberAttribute()]
        public global::System.String PatientID
        {
            get
            {
                return _PatientID;
            }
            set
            {
                if (_PatientID != value)
                {
                    OnPatientIDChanging(value);
                    ReportPropertyChanging("PatientID");
                    _PatientID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("PatientID");
                    OnPatientIDChanged();
                }
            }
        }
        private global::System.String _PatientID;
        partial void OnPatientIDChanging(global::System.String value);
        partial void OnPatientIDChanged();
<<<<<<< HEAD

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = true, IsNullable = false)]
=======
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
>>>>>>> origin/DBconnect
        [DataMemberAttribute()]
        public global::System.String AddressID
        {
            get
            {
                return _AddressID;
            }
            set
            {
                if (_AddressID != value)
                {
                    OnAddressIDChanging(value);
                    ReportPropertyChanging("AddressID");
                    _AddressID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("AddressID");
                    OnAddressIDChanged();
                }
            }
        }
        private global::System.String _AddressID;
        partial void OnAddressIDChanging(global::System.String value);
        partial void OnAddressIDChanged();

        #endregion

<<<<<<< HEAD

    }

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName = "NijnCoachModel", Name = "Questionnairre")]
    [Serializable()]
    [DataContractAttribute(IsReference = true)]
    public partial class Questionnairre : EntityObject
    {
        #region Factory Method

=======
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NijnCoachModel", Name="Questionnairre")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Questionnairre : EntityObject
    {
        #region Factory Method
    
>>>>>>> origin/DBconnect
        /// <summary>
        /// Create a new Questionnairre object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="text">Initial value of the Text property.</param>
        public static Questionnairre CreateQuestionnairre(global::System.SByte id, global::System.String name, global::System.String text)
        {
            Questionnairre questionnairre = new Questionnairre();
            questionnairre.Id = id;
            questionnairre.Name = name;
            questionnairre.Text = text;
            return questionnairre;
        }

        #endregion

        #region Primitive Properties
<<<<<<< HEAD

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
=======
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
>>>>>>> origin/DBconnect
        [DataMemberAttribute()]
        public global::System.SByte Id
        {
            get
            {
                return _Id;
            }
            set
            {
                OnIdChanging(value);
                ReportPropertyChanging("Id");
                _Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Id");
                OnIdChanged();
            }
        }
        private global::System.SByte _Id;
        partial void OnIdChanging(global::System.SByte value);
        partial void OnIdChanged();
<<<<<<< HEAD

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = true, IsNullable = false)]
=======
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
>>>>>>> origin/DBconnect
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                if (_Name != value)
                {
                    OnNameChanging(value);
                    ReportPropertyChanging("Name");
                    _Name = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Name");
                    OnNameChanged();
                }
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
<<<<<<< HEAD

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
=======
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
>>>>>>> origin/DBconnect
        [DataMemberAttribute()]
        public global::System.String Text
        {
            get
            {
                return _Text;
            }
            set
            {
                OnTextChanging(value);
                ReportPropertyChanging("Text");
                _Text = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Text");
                OnTextChanged();
            }
        }
        private global::System.String _Text;
        partial void OnTextChanging(global::System.String value);
        partial void OnTextChanged();

        #endregion

<<<<<<< HEAD

    }

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName = "NijnCoachModel", Name = "SpeechFile")]
    [Serializable()]
    [DataContractAttribute(IsReference = true)]
    public partial class SpeechFile : EntityObject
    {
        #region Factory Method

=======
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NijnCoachModel", Name="SpeechFile")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SpeechFile : EntityObject
    {
        #region Factory Method
    
>>>>>>> origin/DBconnect
        /// <summary>
        /// Create a new SpeechFile object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="encoding">Initial value of the Encoding property.</param>
        public static SpeechFile CreateSpeechFile(global::System.SByte id, global::System.String name, global::System.String encoding)
        {
            SpeechFile speechFile = new SpeechFile();
            speechFile.Id = id;
            speechFile.Name = name;
            speechFile.Encoding = encoding;
            return speechFile;
        }

        #endregion

        #region Primitive Properties
<<<<<<< HEAD

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = true, IsNullable = false)]
=======
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
>>>>>>> origin/DBconnect
        [DataMemberAttribute()]
        public global::System.SByte Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.SByte _Id;
        partial void OnIdChanging(global::System.SByte value);
        partial void OnIdChanged();
<<<<<<< HEAD

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = true, IsNullable = false)]
=======
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
>>>>>>> origin/DBconnect
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                if (_Name != value)
                {
                    OnNameChanging(value);
                    ReportPropertyChanging("Name");
                    _Name = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Name");
                    OnNameChanged();
                }
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
<<<<<<< HEAD

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = true, IsNullable = false)]
=======
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
>>>>>>> origin/DBconnect
        [DataMemberAttribute()]
        public global::System.String Encoding
        {
            get
            {
                return _Encoding;
            }
            set
            {
                if (_Encoding != value)
                {
                    OnEncodingChanging(value);
                    ReportPropertyChanging("Encoding");
                    _Encoding = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Encoding");
                    OnEncodingChanged();
                }
            }
        }
        private global::System.String _Encoding;
        partial void OnEncodingChanging(global::System.String value);
        partial void OnEncodingChanged();

        #endregion

<<<<<<< HEAD

=======
    
>>>>>>> origin/DBconnect
    }

    #endregion

<<<<<<< HEAD

=======
    
>>>>>>> origin/DBconnect
}
