//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace NijnCoach.Database
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class NijnCoachEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new NijnCoachEntities object using the connection string found in the 'NijnCoachEntities' section of the application configuration file.
        /// </summary>
        public NijnCoachEntities() : base("name=NijnCoachEntities", "NijnCoachEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new NijnCoachEntities object.
        /// </summary>
        public NijnCoachEntities(string connectionString) : base(connectionString, "NijnCoachEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new NijnCoachEntities object.
        /// </summary>
        public NijnCoachEntities(EntityConnection connection) : base(connection, "NijnCoachEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Questionnairre> Questionnairres
        {
            get
            {
                if ((_Questionnairres == null))
                {
                    _Questionnairres = base.CreateObjectSet<Questionnairre>("Questionnairres");
                }
                return _Questionnairres;
            }
        }
        private ObjectSet<Questionnairre> _Questionnairres;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SpeechFile> SpeechFiles
        {
            get
            {
                if ((_SpeechFiles == null))
                {
                    _SpeechFiles = base.CreateObjectSet<SpeechFile>("SpeechFiles");
                }
                return _SpeechFiles;
            }
        }
        private ObjectSet<SpeechFile> _SpeechFiles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ProgressEval> ProgressEvals
        {
            get
            {
                if ((_ProgressEvals == null))
                {
                    _ProgressEvals = base.CreateObjectSet<ProgressEval>("ProgressEvals");
                }
                return _ProgressEvals;
            }
        }
        private ObjectSet<ProgressEval> _ProgressEvals;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<User>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<User> _Users;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Sickpeople> Sickpeoples
        {
            get
            {
                if ((_Sickpeoples == null))
                {
                    _Sickpeoples = base.CreateObjectSet<Sickpeople>("Sickpeoples");
                }
                return _Sickpeoples;
            }
        }
        private ObjectSet<Sickpeople> _Sickpeoples;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<AudioFile> AudioFiles
        {
            get
            {
                if ((_AudioFiles == null))
                {
                    _AudioFiles = base.CreateObjectSet<AudioFile>("AudioFiles");
                }
                return _AudioFiles;
            }
        }
        private ObjectSet<AudioFile> _AudioFiles;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Questionnairres EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToQuestionnairres(Questionnairre questionnairre)
        {
            base.AddObject("Questionnairres", questionnairre);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SpeechFiles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSpeechFiles(SpeechFile speechFile)
        {
            base.AddObject("SpeechFiles", speechFile);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ProgressEvals EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProgressEvals(ProgressEval progressEval)
        {
            base.AddObject("ProgressEvals", progressEval);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Sickpeoples EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSickpeoples(Sickpeople sickpeople)
        {
            base.AddObject("Sickpeoples", sickpeople);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the AudioFiles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAudioFiles(AudioFile audioFile)
        {
            base.AddObject("AudioFiles", audioFile);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NijnCoachModel1", Name="AudioFile")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AudioFile : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AudioFile object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="encoding">Initial value of the Encoding property.</param>
        /// <param name="partNo">Initial value of the PartNo property.</param>
        /// <param name="trackNo">Initial value of the TrackNo property.</param>
        public static AudioFile CreateAudioFile(global::System.Int32 id, global::System.String name, global::System.String encoding, global::System.Int32 partNo, global::System.Int32 trackNo)
        {
            AudioFile audioFile = new AudioFile();
            audioFile.Id = id;
            audioFile.Name = name;
            audioFile.Encoding = encoding;
            audioFile.PartNo = partNo;
            audioFile.TrackNo = trackNo;
            return audioFile;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Encoding
        {
            get
            {
                return _Encoding;
            }
            set
            {
                OnEncodingChanging(value);
                ReportPropertyChanging("Encoding");
                _Encoding = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Encoding");
                OnEncodingChanged();
            }
        }
        private global::System.String _Encoding;
        partial void OnEncodingChanging(global::System.String value);
        partial void OnEncodingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PartNo
        {
            get
            {
                return _PartNo;
            }
            set
            {
                OnPartNoChanging(value);
                ReportPropertyChanging("PartNo");
                _PartNo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PartNo");
                OnPartNoChanged();
            }
        }
        private global::System.Int32 _PartNo;
        partial void OnPartNoChanging(global::System.Int32 value);
        partial void OnPartNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TrackNo
        {
            get
            {
                return _TrackNo;
            }
            set
            {
                OnTrackNoChanging(value);
                ReportPropertyChanging("TrackNo");
                _TrackNo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TrackNo");
                OnTrackNoChanged();
            }
        }
        private global::System.Int32 _TrackNo;
        partial void OnTrackNoChanging(global::System.Int32 value);
        partial void OnTrackNoChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NijnCoachModel1", Name="ProgressEval")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ProgressEval : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ProgressEval object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="content">Initial value of the Content property.</param>
        /// <param name="patientNo">Initial value of the PatientNo property.</param>
        /// <param name="emotion">Initial value of the Emotion property.</param>
        public static ProgressEval CreateProgressEval(global::System.String id, global::System.String name, global::System.String content, global::System.Int32 patientNo, global::System.String emotion)
        {
            ProgressEval progressEval = new ProgressEval();
            progressEval.Id = id;
            progressEval.Name = name;
            progressEval.Content = content;
            progressEval.PatientNo = patientNo;
            progressEval.Emotion = emotion;
            return progressEval;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Id
        {
            get
            {
                return _Id;
            }
            set
            {
                OnIdChanging(value);
                ReportPropertyChanging("Id");
                _Id = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Id");
                OnIdChanged();
            }
        }
        private global::System.String _Id;
        partial void OnIdChanging(global::System.String value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                if (_Name != value)
                {
                    OnNameChanging(value);
                    ReportPropertyChanging("Name");
                    _Name = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Name");
                    OnNameChanged();
                }
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Content
        {
            get
            {
                return _Content;
            }
            set
            {
                OnContentChanging(value);
                ReportPropertyChanging("Content");
                _Content = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Content");
                OnContentChanged();
            }
        }
        private global::System.String _Content;
        partial void OnContentChanging(global::System.String value);
        partial void OnContentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PatientNo
        {
            get
            {
                return _PatientNo;
            }
            set
            {
                OnPatientNoChanging(value);
                ReportPropertyChanging("PatientNo");
                _PatientNo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PatientNo");
                OnPatientNoChanged();
            }
        }
        private global::System.Int32 _PatientNo;
        partial void OnPatientNoChanging(global::System.Int32 value);
        partial void OnPatientNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Commentary
        {
            get
            {
                return _Commentary;
            }
            set
            {
                OnCommentaryChanging(value);
                ReportPropertyChanging("Commentary");
                _Commentary = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Commentary");
                OnCommentaryChanged();
            }
        }
        private global::System.String _Commentary;
        partial void OnCommentaryChanging(global::System.String value);
        partial void OnCommentaryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Emotion
        {
            get
            {
                return _Emotion;
            }
            set
            {
                OnEmotionChanging(value);
                ReportPropertyChanging("Emotion");
                _Emotion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Emotion");
                OnEmotionChanged();
            }
        }
        private global::System.String _Emotion;
        partial void OnEmotionChanging(global::System.String value);
        partial void OnEmotionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NijnCoachModel1", Name="Questionnairre")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Questionnairre : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Questionnairre object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="text">Initial value of the Text property.</param>
        /// <param name="forPatient">Initial value of the forPatient property.</param>
        /// <param name="type">Initial value of the Type property.</param>
        /// <param name="filledIn">Initial value of the FilledIn property.</param>
        public static Questionnairre CreateQuestionnairre(global::System.SByte id, global::System.String name, global::System.String text, global::System.SByte forPatient, global::System.String type, global::System.Boolean filledIn)
        {
            Questionnairre questionnairre = new Questionnairre();
            questionnairre.Id = id;
            questionnairre.Name = name;
            questionnairre.Text = text;
            questionnairre.forPatient = forPatient;
            questionnairre.Type = type;
            questionnairre.FilledIn = filledIn;
            return questionnairre;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.SByte Id
        {
            get
            {
                return _Id;
            }
            set
            {
                OnIdChanging(value);
                ReportPropertyChanging("Id");
                _Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Id");
                OnIdChanged();
            }
        }
        private global::System.SByte _Id;
        partial void OnIdChanging(global::System.SByte value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                if (_Name != value)
                {
                    OnNameChanging(value);
                    ReportPropertyChanging("Name");
                    _Name = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Name");
                    OnNameChanged();
                }
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Text
        {
            get
            {
                return _Text;
            }
            set
            {
                OnTextChanging(value);
                ReportPropertyChanging("Text");
                _Text = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Text");
                OnTextChanged();
            }
        }
        private global::System.String _Text;
        partial void OnTextChanging(global::System.String value);
        partial void OnTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.SByte forPatient
        {
            get
            {
                return _forPatient;
            }
            set
            {
                OnforPatientChanging(value);
                ReportPropertyChanging("forPatient");
                _forPatient = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("forPatient");
                OnforPatientChanged();
            }
        }
        private global::System.SByte _forPatient;
        partial void OnforPatientChanging(global::System.SByte value);
        partial void OnforPatientChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.String _Type;
        partial void OnTypeChanging(global::System.String value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean FilledIn
        {
            get
            {
                return _FilledIn;
            }
            set
            {
                OnFilledInChanging(value);
                ReportPropertyChanging("FilledIn");
                _FilledIn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FilledIn");
                OnFilledInChanged();
            }
        }
        private global::System.Boolean _FilledIn;
        partial void OnFilledInChanging(global::System.Boolean value);
        partial void OnFilledInChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NijnCoachModel1", Name="Sickpeople")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Sickpeople : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Sickpeople object.
        /// </summary>
        /// <param name="fname">Initial value of the Fname property.</param>
        /// <param name="lname">Initial value of the Lname property.</param>
        /// <param name="patientNo">Initial value of the PatientNo property.</param>
        /// <param name="age">Initial value of the Age property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        /// <param name="phoneNo">Initial value of the PhoneNo property.</param>
        /// <param name="street">Initial value of the Street property.</param>
        /// <param name="houseNo">Initial value of the HouseNo property.</param>
        /// <param name="postal">Initial value of the Postal property.</param>
        /// <param name="city">Initial value of the City property.</param>
        public static Sickpeople CreateSickpeople(global::System.String fname, global::System.String lname, global::System.Int32 patientNo, global::System.Int32 age, global::System.String email, global::System.Int32 phoneNo, global::System.String street, global::System.Int32 houseNo, global::System.String postal, global::System.String city)
        {
            Sickpeople sickpeople = new Sickpeople();
            sickpeople.Fname = fname;
            sickpeople.Lname = lname;
            sickpeople.PatientNo = patientNo;
            sickpeople.Age = age;
            sickpeople.Email = email;
            sickpeople.PhoneNo = phoneNo;
            sickpeople.Street = street;
            sickpeople.HouseNo = houseNo;
            sickpeople.Postal = postal;
            sickpeople.City = city;
            return sickpeople;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Fname
        {
            get
            {
                return _Fname;
            }
            set
            {
                OnFnameChanging(value);
                ReportPropertyChanging("Fname");
                _Fname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Fname");
                OnFnameChanged();
            }
        }
        private global::System.String _Fname;
        partial void OnFnameChanging(global::System.String value);
        partial void OnFnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Lname
        {
            get
            {
                return _Lname;
            }
            set
            {
                OnLnameChanging(value);
                ReportPropertyChanging("Lname");
                _Lname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Lname");
                OnLnameChanged();
            }
        }
        private global::System.String _Lname;
        partial void OnLnameChanging(global::System.String value);
        partial void OnLnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PatientNo
        {
            get
            {
                return _PatientNo;
            }
            set
            {
                if (_PatientNo != value)
                {
                    OnPatientNoChanging(value);
                    ReportPropertyChanging("PatientNo");
                    _PatientNo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PatientNo");
                    OnPatientNoChanged();
                }
            }
        }
        private global::System.Int32 _PatientNo;
        partial void OnPatientNoChanging(global::System.Int32 value);
        partial void OnPatientNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Age
        {
            get
            {
                return _Age;
            }
            set
            {
                OnAgeChanging(value);
                ReportPropertyChanging("Age");
                _Age = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Age");
                OnAgeChanged();
            }
        }
        private global::System.Int32 _Age;
        partial void OnAgeChanging(global::System.Int32 value);
        partial void OnAgeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PhoneNo
        {
            get
            {
                return _PhoneNo;
            }
            set
            {
                OnPhoneNoChanging(value);
                ReportPropertyChanging("PhoneNo");
                _PhoneNo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PhoneNo");
                OnPhoneNoChanged();
            }
        }
        private global::System.Int32 _PhoneNo;
        partial void OnPhoneNoChanging(global::System.Int32 value);
        partial void OnPhoneNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Street
        {
            get
            {
                return _Street;
            }
            set
            {
                OnStreetChanging(value);
                ReportPropertyChanging("Street");
                _Street = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Street");
                OnStreetChanged();
            }
        }
        private global::System.String _Street;
        partial void OnStreetChanging(global::System.String value);
        partial void OnStreetChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 HouseNo
        {
            get
            {
                return _HouseNo;
            }
            set
            {
                OnHouseNoChanging(value);
                ReportPropertyChanging("HouseNo");
                _HouseNo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HouseNo");
                OnHouseNoChanged();
            }
        }
        private global::System.Int32 _HouseNo;
        partial void OnHouseNoChanging(global::System.Int32 value);
        partial void OnHouseNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Postal
        {
            get
            {
                return _Postal;
            }
            set
            {
                OnPostalChanging(value);
                ReportPropertyChanging("Postal");
                _Postal = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Postal");
                OnPostalChanged();
            }
        }
        private global::System.String _Postal;
        partial void OnPostalChanging(global::System.String value);
        partial void OnPostalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NijnCoachModel1", Name="SpeechFile")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SpeechFile : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SpeechFile object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="encoding">Initial value of the Encoding property.</param>
        /// <param name="trackNo">Initial value of the trackNo property.</param>
        /// <param name="partNo">Initial value of the PartNo property.</param>
        public static SpeechFile CreateSpeechFile(global::System.SByte id, global::System.String name, global::System.String encoding, global::System.Int64 trackNo, global::System.Int32 partNo)
        {
            SpeechFile speechFile = new SpeechFile();
            speechFile.Id = id;
            speechFile.Name = name;
            speechFile.Encoding = encoding;
            speechFile.trackNo = trackNo;
            speechFile.PartNo = partNo;
            return speechFile;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.SByte Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.SByte _Id;
        partial void OnIdChanging(global::System.SByte value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Encoding
        {
            get
            {
                return _Encoding;
            }
            set
            {
                OnEncodingChanging(value);
                ReportPropertyChanging("Encoding");
                _Encoding = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Encoding");
                OnEncodingChanged();
            }
        }
        private global::System.String _Encoding;
        partial void OnEncodingChanging(global::System.String value);
        partial void OnEncodingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 trackNo
        {
            get
            {
                return _trackNo;
            }
            set
            {
                OntrackNoChanging(value);
                ReportPropertyChanging("trackNo");
                _trackNo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("trackNo");
                OntrackNoChanged();
            }
        }
        private global::System.Int64 _trackNo;
        partial void OntrackNoChanging(global::System.Int64 value);
        partial void OntrackNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PartNo
        {
            get
            {
                return _PartNo;
            }
            set
            {
                OnPartNoChanging(value);
                ReportPropertyChanging("PartNo");
                _PartNo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PartNo");
                OnPartNoChanged();
            }
        }
        private global::System.Int32 _PartNo;
        partial void OnPartNoChanging(global::System.Int32 value);
        partial void OnPartNoChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NijnCoachModel1", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="username">Initial value of the Username property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        /// <param name="type">Initial value of the Type property.</param>
        /// <param name="patientNo">Initial value of the PatientNo property.</param>
        public static User CreateUser(global::System.String username, global::System.String password, global::System.String type, global::System.SByte patientNo)
        {
            User user = new User();
            user.Username = username;
            user.Password = password;
            user.Type = type;
            user.PatientNo = patientNo;
            return user;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Username
        {
            get
            {
                return _Username;
            }
            set
            {
                if (_Username != value)
                {
                    OnUsernameChanging(value);
                    ReportPropertyChanging("Username");
                    _Username = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Username");
                    OnUsernameChanged();
                }
            }
        }
        private global::System.String _Username;
        partial void OnUsernameChanging(global::System.String value);
        partial void OnUsernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.String _Type;
        partial void OnTypeChanging(global::System.String value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.SByte PatientNo
        {
            get
            {
                return _PatientNo;
            }
            set
            {
                OnPatientNoChanging(value);
                ReportPropertyChanging("PatientNo");
                _PatientNo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PatientNo");
                OnPatientNoChanged();
            }
        }
        private global::System.SByte _PatientNo;
        partial void OnPatientNoChanging(global::System.SByte value);
        partial void OnPatientNoChanged();

        #endregion

    
    }

    #endregion

    
}
