//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NijnCoach.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NijnCoach.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- edited by Elgar de Groot --&gt;
        ///&lt;questionnaire version=&quot;0.1&quot;&gt;
        ///	&lt;header&gt;
        ///		&lt;questionnaireNumber&gt;1&lt;/questionnaireNumber&gt;
        ///		&lt;created&gt;
        ///			&lt;therapist&gt;E.M.J. de Groot&lt;/therapist&gt;
        ///			&lt;date&gt;
        ///				&lt;day&gt;27&lt;/day&gt;
        ///				&lt;month&gt;03&lt;/month&gt;
        ///				&lt;year&gt;2013&lt;/year&gt;
        ///			&lt;/date&gt;
        ///		&lt;/created&gt;
        ///		&lt;filled&gt;
        ///			&lt;patient&gt;&lt;/patient&gt;
        ///			&lt;date&gt;
        ///				&lt;day&gt;&lt;/day&gt;
        ///				&lt;month&gt;&lt;/month&gt;
        ///				&lt;year&gt;&lt;/year&gt;
        ///			&lt;/date&gt;
        ///			&lt;time&gt;&lt;/time&gt;
        ///		&lt;/filled&gt;
        ///	&lt;/header&gt;
        ///	&lt;entries&gt;
        ///		&lt;entry type=&quot;radio&quot;&gt;
        ///			&lt;question&gt;
        ///				&lt;value&gt;How many [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string testXML {
            get {
                return ResourceManager.GetString("testXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;Questionnaire xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; version=&quot;1&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;questionnaireNumber&gt;0&lt;/questionnaireNumber&gt;
        ///    &lt;createdBy&gt;Me&lt;/createdBy&gt;
        ///    &lt;createdDate&gt;0001-01-01T00:00:00&lt;/createdDate&gt;
        ///    &lt;filledBy&gt;Him&lt;/filledBy&gt;
        ///    &lt;filledDate&gt;0001-01-01T00:00:00&lt;/filledDate&gt;
        ///  &lt;/head&gt;
        ///  &lt;entries&gt;
        ///    &lt;IEntry AssemblyQualifiedName=&quot;NijnCoach.XMLclasses.Comment, NijnCoach, Version=0.0.0.0, Cul [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string writeTest {
            get {
                return ResourceManager.GetString("writeTest", resourceCulture);
            }
        }
    }
}
